name: Run Dummy Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-dummy-test-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Dummy Test Action
      uses: ./
      with:
        input-string: "Test string"
        input-choice: "nvidia"