name: Run Dummy Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      input-string:
        description: 'Input string for the action'
        required: true
        default: 'Test string'
      input-choice:
        description: 'Input choice for the action'
        required: true
        type: choice
        default: 'nvidia'
        options:
          - nvidia
          - amd
          - intel

jobs:
  run-dummy-test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dummy Test Action
        uses: ./test-github-actions
        with:
          input-string: "Test string"
          input-choice: "nvidia"